### ISSUE TITLE
question

### ISSUE THREAD

**Issue by skullcheat** [NaiJii/Apex-Mizu-Base#1]
thanks you

**Comment by skullcheat** [comment]
can you update please =(

**Comment by NaiJii** [comment]
I won't support this base further, the follow up is left as an exercise.
(especially if you're gonna sell that src)

**Comment by skullcheat** [comment]
(especially if you're gonna sell that src)
HAHAHAAAHHA i don't fucking care about your sucked source

**Comment by NaiJii** [comment]
"""can you update please =("""
